/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogAnagrafica.java
 *
 * Created on 21-set-2012, 11.43.49
 */
package viste;

import controllo.FrontController;
import eccezioni.EccezioneChiaveDuplicata;
import eccezioni.EccezioneValoreCampoTroppoLungo;
import entita.Fornitore;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Michele
 */
public class DatiAnagrafica extends javax.swing.JDialog {

    /** Creates new form DialogAnagrafica */
    public DatiAnagrafica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = (Fornitori_Clienti) parent;
        ColorManager color = new ColorManager();
        color.changeColor(pnlDati);
        color.changeColor(pnlRef1);
        color.changeColor(pnlRef2);
        color.changeColor(pnlSedeLegale);
        color.changeColor(pnlSedeOperativa);
        txtIban.setDocument(new JTextFieldLimit(MAX_LENGTH_IBAN));
        txtPIva.setDocument(new JTextFieldLimit(MAX_LENGTH_PIVA));
        txtCodFisc.setDocument(new JTextFieldLimit(MAX_LENGTH_CODFISC));
        txtCapLeg.setDocument(new JTextFieldLimit(MAX_LENGTH_CAP));
        btnModPiva.setVisible(false);
    }
    
    public DatiAnagrafica(java.awt.Frame parent, boolean modal, Fornitore anagrafica) {
        this(parent, modal);
        this.anagrafica = anagrafica;
        btnModPiva.setVisible(true);
        btnModPiva.setEnabled(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDati = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtBanca = new javax.swing.JTextField();
        txtPIva = new javax.swing.JTextField();
        lblCodFisc = new javax.swing.JLabel();
        lblIban = new javax.swing.JLabel();
        lblTit = new javax.swing.JLabel();
        txtIban = new javax.swing.JTextField();
        txtCodFisc = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblBanca = new javax.swing.JLabel();
        lblTel1 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCod = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblPIva = new javax.swing.JLabel();
        txtTitolare = new javax.swing.JTextField();
        lblTel2 = new javax.swing.JLabel();
        txtTelefono2 = new javax.swing.JTextField();
        lblFax = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        txtIscrizioneAlbo = new javax.swing.JTextField();
        lblIban1 = new javax.swing.JLabel();
        pnlRef1 = new javax.swing.JPanel();
        lblNomeRef1 = new javax.swing.JLabel();
        lblEmailRef1 = new javax.swing.JLabel();
        lblTelRef1 = new javax.swing.JLabel();
        txtNomeRef1 = new javax.swing.JTextField();
        txtEmailRef1 = new javax.swing.JTextField();
        txtTelRef1 = new javax.swing.JTextField();
        pnlRef2 = new javax.swing.JPanel();
        lblNomeRef2 = new javax.swing.JLabel();
        lblEmailRef2 = new javax.swing.JLabel();
        lblTelRef2 = new javax.swing.JLabel();
        txtNomeRef2 = new javax.swing.JTextField();
        txtEmailRef2 = new javax.swing.JTextField();
        txtTelRef2 = new javax.swing.JTextField();
        btnModPiva = new javax.swing.JButton();
        btnConferma = new javax.swing.JButton();
        pnlSedeLegale = new javax.swing.JPanel();
        txtProvLeg = new javax.swing.JTextField();
        lblNazione = new javax.swing.JLabel();
        lblProvi = new javax.swing.JLabel();
        lblCap = new javax.swing.JLabel();
        txtIndirizzoLeg = new javax.swing.JTextField();
        txtCapLeg = new javax.swing.JTextField();
        txtNazioneLeg = new javax.swing.JTextField();
        txtCittaLeg = new javax.swing.JTextField();
        lblCitta = new javax.swing.JLabel();
        lblIndirizzo = new javax.swing.JLabel();
        pnlSedeOperativa = new javax.swing.JPanel();
        txtProvOp = new javax.swing.JTextField();
        lblNazione1 = new javax.swing.JLabel();
        lblProvi1 = new javax.swing.JLabel();
        lblCap1 = new javax.swing.JLabel();
        txtIndirizzoOp = new javax.swing.JTextField();
        txtCapOp = new javax.swing.JTextField();
        txtNazioneOp = new javax.swing.JTextField();
        txtCittaOp = new javax.swing.JTextField();
        lblCitta1 = new javax.swing.JLabel();
        lblIndirizzo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlDati.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dati Generali", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lblEmail.setText("E-Mail");
        lblEmail.setToolTipText("");

        txtEmail.setNextFocusableComponent(txtTelefono1);

        txtBanca.setNextFocusableComponent(txtIban);

        txtPIva.setNextFocusableComponent(txtCodFisc);

        lblCodFisc.setText("Codice Fiscale");

        lblIban.setText("IBAN");
        lblIban.setToolTipText("");

        lblTit.setText("di");
        lblTit.setToolTipText("");

        txtIban.setNextFocusableComponent(txtIscrizioneAlbo);

        txtCodFisc.setNextFocusableComponent(txtBanca);

        lblNome.setText("Nome");
        lblNome.setToolTipText("");

        lblBanca.setText("Banca");

        lblTel1.setText("Telefono 1");
        lblTel1.setToolTipText("");

        txtTelefono1.setNextFocusableComponent(txtTelefono2);

        txtNome.setNextFocusableComponent(txtTitolare);

        txtCod.setEnabled(false);

        lblID.setText("Cod.");
        lblID.setToolTipText("");

        lblPIva.setText("Partita IVA");

        txtTitolare.setNextFocusableComponent(txtPIva);

        lblTel2.setText("Telefono 2");
        lblTel2.setToolTipText("");

        txtTelefono2.setNextFocusableComponent(txtFax);

        lblFax.setText("Fax");
        lblFax.setToolTipText("");

        txtFax.setNextFocusableComponent(txtIndirizzoLeg);

        txtIscrizioneAlbo.setNextFocusableComponent(txtEmail);

        lblIban1.setText("Iscrizione all'albo");
        lblIban1.setToolTipText("");

        javax.swing.GroupLayout pnlDatiLayout = new javax.swing.GroupLayout(pnlDati);
        pnlDati.setLayout(pnlDatiLayout);
        pnlDatiLayout.setHorizontalGroup(
            pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatiLayout.createSequentialGroup()
                                .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addGap(58, 58, 58))
                            .addGroup(pnlDatiLayout.createSequentialGroup()
                                .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(pnlDatiLayout.createSequentialGroup()
                                .addComponent(lblPIva)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(pnlDatiLayout.createSequentialGroup()
                                .addComponent(lblCodFisc, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(pnlDatiLayout.createSequentialGroup()
                                .addComponent(lblBanca, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(pnlDatiLayout.createSequentialGroup()
                            .addComponent(lblIban, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(pnlDatiLayout.createSequentialGroup()
                        .addComponent(lblIban1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPIva, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodFisc, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBanca, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIban, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIscrizioneAlbo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFax, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitolare, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlDatiLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBanca, txtCod, txtCodFisc, txtEmail, txtFax, txtIban, txtIscrizioneAlbo, txtNome, txtPIva, txtTelefono1, txtTelefono2, txtTitolare});

        pnlDatiLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblEmail, lblFax, lblTel1, lblTel2, lblTit});

        pnlDatiLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblBanca, lblCodFisc, lblID, lblIban, lblIban1, lblNome, lblPIva});

        pnlDatiLayout.setVerticalGroup(
            pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(lblTit)
                    .addComponent(txtTitolare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPIva)
                    .addComponent(txtPIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodFisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodFisc)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBanca)
                    .addComponent(lblTel1)
                    .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIban)
                    .addComponent(txtIban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTel2)
                    .addComponent(txtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIban1)
                    .addComponent(txtIscrizioneAlbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFax))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatiLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblIban1, txtIscrizioneAlbo});

        pnlDatiLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblIban, txtIban});

        pnlDatiLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblBanca, txtBanca});

        pnlDatiLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCodFisc, txtCodFisc});

        pnlDatiLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblPIva, txtPIva});

        pnlDatiLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblNome, txtNome});

        pnlDatiLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblID, txtCod});

        pnlDatiLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblTit, txtTitolare});

        pnlDatiLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblEmail, txtEmail});

        pnlDatiLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblTel1, txtTelefono1});

        pnlDatiLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblTel2, txtTelefono2});

        pnlDatiLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblFax, txtFax});

        pnlRef1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Referente 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lblNomeRef1.setText("Nome");

        lblEmailRef1.setText("E-Mail");

        lblTelRef1.setText("Telefono");

        txtNomeRef1.setNextFocusableComponent(txtEmailRef1);

        txtEmailRef1.setNextFocusableComponent(txtTelRef1);

        txtTelRef1.setNextFocusableComponent(txtNomeRef2);

        javax.swing.GroupLayout pnlRef1Layout = new javax.swing.GroupLayout(pnlRef1);
        pnlRef1.setLayout(pnlRef1Layout);
        pnlRef1Layout.setHorizontalGroup(
            pnlRef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRef1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelRef1)
                    .addComponent(lblEmailRef1)
                    .addComponent(lblNomeRef1))
                .addGap(28, 28, 28)
                .addGroup(pnlRef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmailRef1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelRef1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeRef1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlRef1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEmailRef1, txtNomeRef1, txtTelRef1});

        pnlRef1Layout.setVerticalGroup(
            pnlRef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRef1Layout.createSequentialGroup()
                .addGroup(pnlRef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeRef1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeRef1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailRef1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailRef1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRef1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelRef1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelRef1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRef2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Referente 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lblNomeRef2.setText("Nome");

        lblEmailRef2.setText("E-Mail");

        lblTelRef2.setText("Telefono");

        txtNomeRef2.setNextFocusableComponent(txtEmailRef2);

        txtEmailRef2.setNextFocusableComponent(txtTelRef2);

        txtTelRef2.setNextFocusableComponent(txtNome);

        javax.swing.GroupLayout pnlRef2Layout = new javax.swing.GroupLayout(pnlRef2);
        pnlRef2.setLayout(pnlRef2Layout);
        pnlRef2Layout.setHorizontalGroup(
            pnlRef2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRef2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRef2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelRef2)
                    .addComponent(lblEmailRef2)
                    .addComponent(lblNomeRef2))
                .addGap(28, 28, 28)
                .addGroup(pnlRef2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmailRef2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelRef2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeRef2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlRef2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEmailRef2, txtNomeRef2, txtTelRef2});

        pnlRef2Layout.setVerticalGroup(
            pnlRef2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRef2Layout.createSequentialGroup()
                .addGroup(pnlRef2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeRef2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeRef2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRef2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailRef2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailRef2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRef2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelRef2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelRef2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnModPiva.setText("Modifica P.Iva");
        btnModPiva.setEnabled(false);
        btnModPiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModPivaActionPerformed(evt);
            }
        });

        btnConferma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        btnConferma.setText("Conferma");
        btnConferma.setToolTipText("Salva il nuovo fornitore");
        btnConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfermaActionPerformed(evt);
            }
        });

        pnlSedeLegale.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Sede legale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lblNazione.setText("Nazione");
        lblNazione.setToolTipText("");

        lblProvi.setText("Provincia");
        lblProvi.setToolTipText("");

        lblCap.setText("CAP");
        lblCap.setToolTipText("");

        lblCitta.setText("Città");
        lblCitta.setToolTipText("");

        lblIndirizzo.setText("Indirizzo");
        lblIndirizzo.setToolTipText("");

        javax.swing.GroupLayout pnlSedeLegaleLayout = new javax.swing.GroupLayout(pnlSedeLegale);
        pnlSedeLegale.setLayout(pnlSedeLegaleLayout);
        pnlSedeLegaleLayout.setHorizontalGroup(
            pnlSedeLegaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSedeLegaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSedeLegaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProvi, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNazione, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCitta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCap, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIndirizzo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSedeLegaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIndirizzoLeg, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCapLeg, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCittaLeg, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProvLeg, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNazioneLeg, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113))
        );

        pnlSedeLegaleLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCap, lblCitta, lblIndirizzo, lblNazione, lblProvi});

        pnlSedeLegaleLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCapLeg, txtCittaLeg, txtIndirizzoLeg, txtNazioneLeg, txtProvLeg});

        pnlSedeLegaleLayout.setVerticalGroup(
            pnlSedeLegaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSedeLegaleLayout.createSequentialGroup()
                .addGroup(pnlSedeLegaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSedeLegaleLayout.createSequentialGroup()
                        .addComponent(txtIndirizzoLeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCapLeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCittaLeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtProvLeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNazioneLeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSedeLegaleLayout.createSequentialGroup()
                        .addComponent(lblIndirizzo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCitta)
                        .addGap(7, 7, 7)
                        .addComponent(lblProvi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNazione)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSedeLegaleLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCap, lblCitta, lblIndirizzo, lblNazione, lblProvi, txtCapLeg, txtCittaLeg, txtIndirizzoLeg, txtNazioneLeg, txtProvLeg});

        pnlSedeOperativa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Sede operativa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lblNazione1.setText("Nazione");
        lblNazione1.setToolTipText("");

        lblProvi1.setText("Provincia");
        lblProvi1.setToolTipText("");

        lblCap1.setText("CAP");
        lblCap1.setToolTipText("");

        txtNazioneOp.setNextFocusableComponent(txtNomeRef1);

        lblCitta1.setText("Città");
        lblCitta1.setToolTipText("");

        lblIndirizzo1.setText("Indirizzo");
        lblIndirizzo1.setToolTipText("");

        javax.swing.GroupLayout pnlSedeOperativaLayout = new javax.swing.GroupLayout(pnlSedeOperativa);
        pnlSedeOperativa.setLayout(pnlSedeOperativaLayout);
        pnlSedeOperativaLayout.setHorizontalGroup(
            pnlSedeOperativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSedeOperativaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSedeOperativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSedeOperativaLayout.createSequentialGroup()
                        .addComponent(lblIndirizzo1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIndirizzoOp, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSedeOperativaLayout.createSequentialGroup()
                        .addComponent(lblCap1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCapOp, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSedeOperativaLayout.createSequentialGroup()
                        .addComponent(lblCitta1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCittaOp, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSedeOperativaLayout.createSequentialGroup()
                        .addComponent(lblProvi1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProvOp, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSedeOperativaLayout.createSequentialGroup()
                        .addComponent(lblNazione1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNazioneOp, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlSedeOperativaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCapOp, txtCittaOp, txtIndirizzoOp, txtNazioneOp, txtProvOp});

        pnlSedeOperativaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCap1, lblCitta1, lblIndirizzo1, lblNazione1, lblProvi1});

        pnlSedeOperativaLayout.setVerticalGroup(
            pnlSedeOperativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSedeOperativaLayout.createSequentialGroup()
                .addGroup(pnlSedeOperativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIndirizzo1)
                    .addComponent(txtIndirizzoOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSedeOperativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCap1)
                    .addComponent(txtCapOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSedeOperativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCittaOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCitta1))
                .addGap(7, 7, 7)
                .addGroup(pnlSedeOperativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProvOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProvi1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSedeOperativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNazione1)
                    .addComponent(txtNazioneOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSedeOperativaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblIndirizzo1, txtIndirizzoOp});

        pnlSedeOperativaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCap1, txtCapOp});

        pnlSedeOperativaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCitta1, txtCittaOp});

        pnlSedeOperativaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblProvi1, txtProvOp});

        pnlSedeOperativaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblNazione1, txtNazioneOp});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlDati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlSedeLegale, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(pnlSedeOperativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConferma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(btnModPiva, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlRef1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRef2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnConferma, btnModPiva});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pnlSedeLegale, pnlSedeOperativa});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlRef1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlRef2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlDati, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModPiva)
                    .addComponent(btnConferma)
                    .addComponent(pnlSedeOperativa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSedeLegale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnConferma, btnModPiva});

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
    if (anagrafica != null) {
        txtCod.setText(anagrafica.getCod().toString());
        txtNome.setText(anagrafica.getNome());
        txtPIva.setText(anagrafica.getPiva());
        txtCodFisc.setText(anagrafica.getCodfiscale());
        txtBanca.setText(anagrafica.getBanca());
        txtIban.setText(anagrafica.getIban());
        txtTelefono1.setText(anagrafica.getTelefono1());
        txtTelefono2.setText(anagrafica.getTelefono2());
        txtFax.setText(anagrafica.getFax());
        txtEmail.setText(anagrafica.getEmail());
        txtTitolare.setText(anagrafica.getTitolare());
        txtIndirizzoLeg.setText(anagrafica.getIndirizzoLeg());
        txtCapLeg.setText(anagrafica.getCapLeg());
        txtCittaLeg.setText(anagrafica.getCittaLeg());
        txtProvLeg.setText(anagrafica.getProvLeg());
        txtNazioneLeg.setText(anagrafica.getNazioneLeg());
        txtNomeRef1.setText(anagrafica.getNomeRef1());
        txtEmailRef1.setText(anagrafica.getEmailRef1());
        txtTelRef1.setText(anagrafica.getTelRef1());
        txtNomeRef2.setText(anagrafica.getNomeRef2());
        txtEmailRef2.setText(anagrafica.getEmailRef2());
        txtTelRef2.setText(anagrafica.getTelRef2());
        txtIscrizioneAlbo.setText(anagrafica.getIscrizioneAlbo());
        txtIndirizzoOp.setText(anagrafica.getIndirizzoOp());
        txtCapOp.setText(anagrafica.getCapOp());
        txtCittaOp.setText(anagrafica.getCittaOp());
        txtProvOp.setText(anagrafica.getProvOp());
        txtNazioneOp.setText(anagrafica.getNazioneOp());
        setTitle("Modifica " + anagrafica);
        
    } else {
        setTitle("Nuova anagrafica");
    }
}//GEN-LAST:event_formWindowOpened

/*
 * Controlla che l'email rispetti il formato consueto.
 */
private boolean checkEmail(String email) {
    if (email.isEmpty())
        return true;
    
    Pattern pattern = Pattern.compile(".+@.+\\.[a-z]+");
    Matcher match = pattern.matcher(email);
    return match.matches();
}

private void btnModPivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModPivaActionPerformed
// TODO add your handling code here:
    boolean ok = false;
    String newPiva = null;
    while (!ok) {
        newPiva = JOptionPane.showInputDialog("Stai per creare un nuovo fornitore mantenendo i dati selezionati. Inserisci la nuova Partita IVA per continuare");
        ok = true;
        if (newPiva != null) {
            if (newPiva.length() != MAX_LENGTH_PIVA) {
                JOptionPane.showMessageDialog(rootPane, "La Partita IVA deve contenere " + MAX_LENGTH_PIVA + " valori");
                ok = false;
            } else {
                String nome = txtNome.getText();
                String titolare = txtTitolare.getText();
                String codfisc = newPiva;
                String indirizzoLeg = txtIndirizzoLeg.getText();
                String telefono1 = txtTelefono1.getText();
                String telefono2 = txtTelefono2.getText();
                String fax = txtFax.getText();
                String email = txtEmail.getText();
                String capLeg = txtCapLeg.getText();
                String cittaLeg = txtCittaLeg.getText();
                String provLeg = txtProvLeg.getText().toUpperCase();
                String nazioneLeg = txtNazioneLeg.getText();
                String banca = txtBanca.getText();
                String iban = txtIban.getText().toUpperCase();
                String nomeRef1 = txtNomeRef1.getText();
                String nomeRef2 = txtNomeRef2.getText();
                String emailRef1 = txtEmailRef1.getText();
                String emailRef2 = txtEmailRef2.getText();
                String telRef1 = txtTelRef1.getText();
                String telRef2 = txtTelRef2.getText();
                String iscrizioneAlbo = txtIscrizioneAlbo.getText();
                String indirizzoOp = txtIndirizzoOp.getText();
                String capOp = txtCapOp.getText();
                String cittaOp = txtCittaOp.getText();
                String provOp = txtProvOp.getText().toUpperCase();
                String nazioneOp = txtNazioneOp.getText();
    
                Fornitore fornitore = new Fornitore(null, nome, titolare, newPiva, codfisc, indirizzoLeg, telefono1, telefono2, fax, email, capLeg, cittaLeg, provLeg, nazioneLeg, banca, iban,
                        iscrizioneAlbo, indirizzoOp, cittaOp, capOp, provOp, nazioneOp, nomeRef1, nomeRef2, emailRef1, emailRef2, telRef1, telRef2);
                try {
                    if (FrontController.insert(fornitore)) {
                        parent.visualizzaDati();
                        JOptionPane.showMessageDialog(null, "Inserimento eseguito con successo!", "", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                    } else
                        JOptionPane.showMessageDialog(null, "Si è verificato un errore durante l'inserimento", "Errore" ,JOptionPane.ERROR_MESSAGE);
                    
                } catch (EccezioneChiaveDuplicata e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Errore" ,JOptionPane.ERROR_MESSAGE);
                } catch (EccezioneValoreCampoTroppoLungo e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Errore" ,JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }
    
}//GEN-LAST:event_btnModPivaActionPerformed

private void btnConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermaActionPerformed
    // TODO add your handling code here:
    String cod = txtCod.getText();
    String nome = txtNome.getText();
    String titolare = txtTitolare.getText();
    String piva = txtPIva.getText();
    String codfisc = txtCodFisc.getText();
    String indirizzoLeg = txtIndirizzoLeg.getText();
    String telefono1 = txtTelefono1.getText();
    String telefono2 = txtTelefono2.getText();
    String fax = txtFax.getText();
    String email = txtEmail.getText();
    String capLeg = txtCapLeg.getText();
    String cittaLeg = txtCittaLeg.getText();
    String provLeg = txtProvLeg.getText().toUpperCase();
    String nazioneLeg = txtNazioneLeg.getText();
    String banca = txtBanca.getText();
    String iban = txtIban.getText().toUpperCase();
    String nomeRef1 = txtNomeRef1.getText();
    String nomeRef2 = txtNomeRef2.getText();
    String emailRef1 = txtEmailRef1.getText();
    String emailRef2 = txtEmailRef2.getText();
    String telRef1 = txtTelRef1.getText();
    String telRef2 = txtTelRef2.getText();
    String iscrizioneAlbo = txtIscrizioneAlbo.getText();
    String indirizzoOp = txtIndirizzoOp.getText();
    String capOp = txtCapOp.getText();
    String cittaOp = txtCittaOp.getText();
    String provOp = txtProvOp.getText().toUpperCase();
    String nazioneOp = txtNazioneOp.getText();

    
    Integer COD = null;
    try {
        COD = Integer.parseInt(cod);
        
    } catch (NumberFormatException e) {}
        
    /*
     * Vengono effettuati dei controlli sui valori inseriti, mostrando degli opportuni messaggi nel caso in cui
     * tali valori non rispettano il formato corretto.
     */
    boolean checkData=true;
    if (piva.isEmpty() && codfisc.isEmpty()){
        JOptionPane.showMessageDialog(null, "Inserire la Partita IVA o il Codice fiscale!", "Campo obbligatorio mancante", JOptionPane.ERROR_MESSAGE);
        checkData=false;
        
    } else { 
        if (!piva.isEmpty() && piva.length() != MAX_LENGTH_PIVA){
            JOptionPane.showMessageDialog(null, "La Partita IVA deve contenere " + MAX_LENGTH_PIVA + " cifre!", "Campo obbligatorio errato", JOptionPane.ERROR_MESSAGE);
            checkData=false;
        } 
        
        if (!codfisc.isEmpty() && codfisc.length() != MAX_LENGTH_CODFISC) {
            JOptionPane.showMessageDialog(null, "Il codice fiscale deve contenere " + MAX_LENGTH_CODFISC + " cifre!", "Campo obbligatorio errato", JOptionPane.ERROR_MESSAGE);
            checkData=false;
        }
        
        if (!checkEmail(email)) {
            JOptionPane.showMessageDialog(null, "Inserire l'E-Mail nel formato corretto!", "Formato errato", JOptionPane.ERROR_MESSAGE);
            checkData=false;
        }
        
        if (!checkEmail(emailRef1)) {
            JOptionPane.showMessageDialog(null, "Inserire l'E-Mail del referente 1 nel formato corretto!", "Formato errato", JOptionPane.ERROR_MESSAGE);
            checkData=false;
        }
        
        if (!checkEmail(emailRef2)) {
            JOptionPane.showMessageDialog(null, "Inserire l'E-Mail del referente 2 nel formato corretto!", "Formato errato", JOptionPane.ERROR_MESSAGE);
            checkData=false;
        }
        
        if (!capLeg.isEmpty() && capLeg.length() != MAX_LENGTH_CAP) {
            JOptionPane.showMessageDialog(null, "Il CAP legale deve contenere " + MAX_LENGTH_CAP + " cifre!", "Formato errato", JOptionPane.ERROR_MESSAGE);
            checkData=false;
        }
        
        if (!capOp.isEmpty() && capOp.length() != MAX_LENGTH_CAP) {
            JOptionPane.showMessageDialog(null, "Il CAP operativo deve contenere " + MAX_LENGTH_CAP + " cifre!", "Formato errato", JOptionPane.ERROR_MESSAGE);
            checkData=false;
        }
        
        if (!iban.isEmpty() && iban.length() != MAX_LENGTH_IBAN) {
            JOptionPane.showMessageDialog(null, "Il codice IBAN deve contenere " + MAX_LENGTH_IBAN + " cifre!", "Formato errato", JOptionPane.ERROR_MESSAGE);
            checkData=false;
        }
    } 
    
    /*
     * Se i campi non contengono errori di formato, si cerca di inserire un nuovo fornitore, o di aggiornare 
     * un fornitore esistente, rispettivamente se non è stata selezionata alcuna riga, o è stata selezionata una 
     * riga della tabella.
     */
    if (checkData){
        Fornitore fornitore = new Fornitore(COD, nome, titolare, piva, codfisc, indirizzoLeg, telefono1, telefono2, fax, email, capLeg, cittaLeg, provLeg, nazioneLeg, banca, iban,
                iscrizioneAlbo, indirizzoOp, cittaOp, capOp, provOp, nazioneOp, nomeRef1, nomeRef2, emailRef1, emailRef2, telRef1, telRef2);
        
        /*
         * Se l'id è != null vuol dire che è stata selezionata una riga dalla tabella, quindi si cerca di 
         * aggiornare i campi rispettivi, altrimenti vuol dire che non è stata selezionata alcuna riga. In 
         * questo caso si cerca di inserire una nuova riga.
         */
        if (COD != null) {
            final int RESPONSE = JOptionPane.showConfirmDialog(null, "Sei sicuro di voler procedere con la modifica?", "Conferma modifica", JOptionPane.OK_CANCEL_OPTION);
            if (RESPONSE == JOptionPane.OK_OPTION) {
                try {
                    if (FrontController.update(fornitore)) {
                        parent.visualizzaDati();
                        JOptionPane.showMessageDialog(null, "Modifica eseguita con successo!", "", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                    }
                        
                    else
                        JOptionPane.showMessageDialog(null, "Si è verificato un errore durante la modifica", "Errore" ,JOptionPane.ERROR_MESSAGE);
                
                } catch (EccezioneChiaveDuplicata e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Errore" ,JOptionPane.ERROR_MESSAGE);
                
                } catch (EccezioneValoreCampoTroppoLungo e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Errore" ,JOptionPane.ERROR_MESSAGE);
                }
            }
        
        } else {
            final int RESPONSE = JOptionPane.showConfirmDialog(null, "Sei sicuro di voler procedere con l'inserimento?", "Conferma inserimento", JOptionPane.OK_CANCEL_OPTION);
            if (RESPONSE == JOptionPane.OK_OPTION) {
                try {
                    if (FrontController.insert(fornitore)) {
                        parent.visualizzaDati();
                        JOptionPane.showMessageDialog(null, "Inserimento eseguito con successo!", "", JOptionPane.INFORMATION_MESSAGE);
                        pulisciText();
                    }
                        
                    else
                        JOptionPane.showMessageDialog(null, "Si è verificato un errore durante l'inserimento", "Errore" ,JOptionPane.ERROR_MESSAGE);
                
                } catch (EccezioneChiaveDuplicata e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Errore" ,JOptionPane.ERROR_MESSAGE);
                } catch (EccezioneValoreCampoTroppoLungo e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Errore" ,JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
    } 
    
}//GEN-LAST:event_btnConfermaActionPerformed

private void pulisciText() {
    txtCod.setText(null);
    txtNome.setText(null);
    txtTitolare.setText(null);
    txtPIva.setText(null);
    txtCodFisc.setText(null);
    txtTelefono1.setText(null);
    txtTelefono2.setText(null);
    txtFax.setText(null);
    txtCapLeg.setText(null);
    txtCittaLeg.setText(null);
    txtProvLeg.setText(null);
    txtNazioneLeg.setText(null);
    txtBanca.setText(null);
    txtIban.setText(null);
    txtIndirizzoLeg.setText(null);
    txtEmail.setText(null);
    txtNomeRef1.setText(null);
    txtNomeRef2.setText(null);
    txtEmailRef1.setText(null);
    txtEmailRef2.setText(null);
    txtTelRef1.setText(null);
    txtTelRef2.setText(null);
    txtIscrizioneAlbo.setText(null);
    txtIndirizzoOp.setText(null);
    txtCapOp.setText(null);
    txtCittaOp.setText(null);
    txtProvOp.setText(null);
    txtNazioneOp.setText(null);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConferma;
    private javax.swing.JButton btnModPiva;
    private javax.swing.JLabel lblBanca;
    private javax.swing.JLabel lblCap;
    private javax.swing.JLabel lblCap1;
    private javax.swing.JLabel lblCitta;
    private javax.swing.JLabel lblCitta1;
    private javax.swing.JLabel lblCodFisc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailRef1;
    private javax.swing.JLabel lblEmailRef2;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIban;
    private javax.swing.JLabel lblIban1;
    private javax.swing.JLabel lblIndirizzo;
    private javax.swing.JLabel lblIndirizzo1;
    private javax.swing.JLabel lblNazione;
    private javax.swing.JLabel lblNazione1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeRef1;
    private javax.swing.JLabel lblNomeRef2;
    private javax.swing.JLabel lblPIva;
    private javax.swing.JLabel lblProvi;
    private javax.swing.JLabel lblProvi1;
    private javax.swing.JLabel lblTel1;
    private javax.swing.JLabel lblTel2;
    private javax.swing.JLabel lblTelRef1;
    private javax.swing.JLabel lblTelRef2;
    private javax.swing.JLabel lblTit;
    private javax.swing.JPanel pnlDati;
    private javax.swing.JPanel pnlRef1;
    private javax.swing.JPanel pnlRef2;
    private javax.swing.JPanel pnlSedeLegale;
    private javax.swing.JPanel pnlSedeOperativa;
    private javax.swing.JTextField txtBanca;
    private javax.swing.JTextField txtCapLeg;
    private javax.swing.JTextField txtCapOp;
    private javax.swing.JTextField txtCittaLeg;
    private javax.swing.JTextField txtCittaOp;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtCodFisc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailRef1;
    private javax.swing.JTextField txtEmailRef2;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtIban;
    private javax.swing.JTextField txtIndirizzoLeg;
    private javax.swing.JTextField txtIndirizzoOp;
    private javax.swing.JTextField txtIscrizioneAlbo;
    private javax.swing.JTextField txtNazioneLeg;
    private javax.swing.JTextField txtNazioneOp;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeRef1;
    private javax.swing.JTextField txtNomeRef2;
    private javax.swing.JTextField txtPIva;
    private javax.swing.JTextField txtProvLeg;
    private javax.swing.JTextField txtProvOp;
    private javax.swing.JTextField txtTelRef1;
    private javax.swing.JTextField txtTelRef2;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JTextField txtTelefono2;
    private javax.swing.JTextField txtTitolare;
    // End of variables declaration//GEN-END:variables

    private Fornitore anagrafica;
    private Fornitori_Clienti parent;
    
    private static final int MAX_LENGTH_IBAN = 27;
    private static final int MAX_LENGTH_PIVA = 11;
    private static final int MAX_LENGTH_CODFISC = 16;
    private static final int MAX_LENGTH_CAP = 5;
}