/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InsFatturaAcquisto.java
 *
 * Created on 6-giu-2012, 20.16.59
 */
package viste;

import controllo.FrontController;
import eccezioni.EccezioneChiaveDuplicata;
import eccezioni.EccezioneValoreCampoTroppoLungo;
import entita.Entity;
import entita.Fattura;
import entita.Fornitore;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Andle
 */
public class InsFatturaAcquisto extends javax.swing.JDialog {

    /** Creates new form InsFatturaAcquisto */
    public InsFatturaAcquisto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Inserimento fattura di acquisto");
        this.parent = (RegistroFattureAcquisto) parent;
        ColorManager color = new ColorManager();
        color.changeColor(pnl);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMemorizza = new javax.swing.JButton();
        pnl = new javax.swing.JPanel();
        cboFornitore = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        txtMeseFatt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAnnoFatt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtGiornoFatt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtImporto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSconto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTotale = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cboMetPag = new javax.swing.JComboBox();
        cboGiorni = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox();
        chkPagata = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        txtNote = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnMemorizza.setBackground(new java.awt.Color(255, 255, 255));
        btnMemorizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnMemorizza.setText("Memorizza");
        btnMemorizza.setMargin(new java.awt.Insets(2, -10, 2, 14));
        btnMemorizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemorizzaActionPerformed(evt);
            }
        });

        pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        cboFornitore.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleziona un fornitore" }));
        cboFornitore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFornitoreActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero");

        jLabel13.setText("gg");

        jLabel14.setText("aaaa");

        jLabel11.setText("Data Fattura");

        jLabel12.setText("mm");

        jLabel2.setText("Importo");

        jLabel3.setText("Sconto");

        jLabel4.setText("Iva");

        jLabel5.setText("Totale");

        jLabel9.setText("Pagamento");

        cboGiorni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "30", "45", "60", "75", "90", "105", "120" }));

        jLabel10.setText("Giorni");

        jLabel8.setText("Tipo Fattura");

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Terzi", "Ricevute", "Stipendi", "Note Credito", "Note Debito", "Polizze", "Varie", "Manutenzione", "Rifornimenti", "Acq. strutture" }));

        chkPagata.setText("Pagata");

        jLabel6.setText("Note");

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboFornitore, 0, 354, Short.MAX_VALUE)
                            .addGroup(pnlLayout.createSequentialGroup()
                                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                        .addComponent(cboMetPag, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLayout.createSequentialGroup()
                                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(pnlLayout.createSequentialGroup()
                                                                .addComponent(jLabel11)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                                                .addComponent(jLabel13)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtGiornoFatt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel12)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                            .addGroup(pnlLayout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addGap(121, 121, 121)))
                                                        .addGroup(pnlLayout.createSequentialGroup()
                                                            .addComponent(jLabel1)
                                                            .addGap(122, 122, 122)))
                                                    .addGroup(pnlLayout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addGap(126, 126, 126)))
                                                .addGroup(pnlLayout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addGap(143, 143, 143)))
                                            .addGroup(pnlLayout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtIva)
                                                .addComponent(txtSconto)
                                                .addComponent(txtNum)
                                                .addComponent(txtImporto)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLayout.createSequentialGroup()
                                                    .addComponent(txtMeseFatt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel14)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtAnnoFatt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(txtTotale, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboGiorni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkPagata)
                            .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96))
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)
                        .addComponent(txtNote, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboFornitore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(txtGiornoFatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtMeseFatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtAnnoFatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtImporto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboGiorni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cboMetPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(chkPagata)
                .addGap(18, 18, 18)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMemorizza, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMemorizza)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
protected void popolaSelect(List items) {
    for (Object item : items)
        cboFornitore.addItem((Fornitore) item);

}
    
private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
    List<Entity> fornitori = FrontController.getAnagrafe(Fornitore.class);
    popolaSelect(fornitori);
    String[] metPagam = FrontController.getMetodiPagamento();
    for (String metodo : metPagam)
        cboMetPag.addItem((String) metodo);
}//GEN-LAST:event_formWindowOpened

private void cboFornitoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFornitoreActionPerformed
// TODO add your handling code here:
    txtNum.requestFocus();
    Fornitore forn = null;
    if (cboFornitore.getSelectedIndex() > 0) {
        forn = (Fornitore) cboFornitore.getSelectedItem();
        codFornitore = forn.getCod();
    } else
        codFornitore = 0;
}//GEN-LAST:event_cboFornitoreActionPerformed

private void btnMemorizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemorizzaActionPerformed
// TODO add your handling code here:
    
    int fornitore;
    if (codFornitore > 0)
        fornitore = codFornitore;
    else {
        JOptionPane.showMessageDialog(this, "Selezionare un fornitore!", "Campo mancante", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String numero = txtNum.getText();
    if (numero.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Inserire il numero della fattura!", "Campo mancante", JOptionPane.WARNING_MESSAGE);
        return;    
    }
        
    int num = 0;
    try {
        num = Integer.parseInt(numero);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Il numero deve essere un numero intero!", "Formato errato", JOptionPane.ERROR_MESSAGE);
        return;
    }
        
    String anno = txtAnnoFatt.getText();
    String mese = txtMeseFatt.getText();
    String giorno = txtGiornoFatt.getText();
    
    if (anno.isEmpty() || mese.isEmpty() || giorno.isEmpty()) { //Un o più campi fra gg, mm e aaaa non sono stati inseriti
        JOptionPane.showMessageDialog(null, "Inserire tutti i campi per la data", 
            "Campo obbligatorio mancante", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    if (anno.length() == 2)
        anno = "20" + anno;
    else if (anno.length() == 3)
        anno = "2" + anno;
    
    if (mese.length() == 1)
        mese = "0" + mese;
    
    if (giorno.length() == 1)
        giorno = "0" + giorno;
    
    Date data = null;
    try {
        data = Date.valueOf(anno + "-" + mese + "-"  + giorno);
        
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(null, "Valore inserito per la data non valido! Inserire la data nel formato gg/mm/aaaa", 
            "Formato errato", JOptionPane.ERROR_MESSAGE);
            return;
    }
    
    String metPag = "Contante-0";
    if (cboMetPag.getSelectedIndex() > 0)
        metPag = String.valueOf(cboMetPag.getSelectedItem()) + "-" + String.valueOf(cboGiorni.getSelectedItem());
    
    String imp = txtImporto.getText();
    if (imp.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Inserire l'importo della fattura!", "Campo mancante", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    double importo = 0.00;
    try {
        importo = Double.parseDouble(imp);
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "L'importo deve essere un numero decimale!", "Formato errato", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    String sc = txtSconto.getText();
    double sconto = 0.00;
    if (!sc.isEmpty()) {
        try {
            sconto = Double.parseDouble(sc);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lo sconto deve essere un numero decimale!", "Formato errato", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }
    
    String textIva = txtIva.getText();
    if (textIva.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Inserire l'IVA!", "Campo mancante", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    double iva = 0.00;
    try {
        iva = Double.parseDouble(textIva);
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "L'iva deve essere un numero decimale!", "Formato errato", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    String tot = txtTotale.getText();
    if (tot.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Inserire il totale della fattura!", "Campo mancante", JOptionPane.WARNING_MESSAGE);
        return;
    }    
    
    double totale = 0.00;
    try {
        totale = Double.parseDouble(tot);
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Il totale deve essere un numero decimale!", "Formato errato", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    String tipo = String.valueOf(cboTipo.getSelectedItem());
        
    boolean pagata = chkPagata.isSelected();
    
    String note = txtNote.getText();
    
    Fattura fatt = new Fattura(num, data, metPag, importo, sconto, iva, totale, tipo, pagata, fornitore, note);
    
    try {
        if (FrontController.insertFattAcquisto(fatt)) {
            parent.setFatture();
            JOptionPane.showMessageDialog(this, "Inserimento fattura eseguito con successo");
            cboFornitore.setSelectedIndex(0);
            txtNum.setText(null);
            txtGiornoFatt.setText(null);
            txtMeseFatt.setText(null);
            txtAnnoFatt.setText(null);
            txtImporto.setText(null);
            txtSconto.setText(null);
            txtIva.setText(null);
            txtTotale.setText(null);
            cboMetPag.setSelectedIndex(0);
            cboGiorni.setSelectedIndex(0);
            cboTipo.setSelectedIndex(0);
            chkPagata.setSelected(false);
        }
        else
            JOptionPane.showMessageDialog(this, "Ci sono stati problemi nell'inserimento, si prega di reinserire i dati", "Errore", JOptionPane.ERROR_MESSAGE);
        
    } catch (EccezioneChiaveDuplicata e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Chiave duplicata", JOptionPane.ERROR_MESSAGE);
        
    } catch (EccezioneValoreCampoTroppoLungo e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "", JOptionPane.ERROR_MESSAGE);
    }
    
}//GEN-LAST:event_btnMemorizzaActionPerformed

    private int codFornitore;
    private RegistroFattureAcquisto parent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMemorizza;
    private javax.swing.JComboBox cboFornitore;
    private javax.swing.JComboBox cboGiorni;
    private javax.swing.JComboBox cboMetPag;
    private javax.swing.JComboBox cboTipo;
    private javax.swing.JCheckBox chkPagata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnl;
    private javax.swing.JTextField txtAnnoFatt;
    private javax.swing.JTextField txtGiornoFatt;
    private javax.swing.JTextField txtImporto;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtMeseFatt;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtSconto;
    private javax.swing.JTextField txtTotale;
    // End of variables declaration//GEN-END:variables
}
