/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModificaModPagamento.java
 *
 * Created on 8-ott-2012, 18.09.07
 */
package viste;

import controllo.FrontController;
import entita.Fattura;
import javax.swing.JOptionPane;

/**
 *
 * @author Michele
 */
public class ModificaModPagamento extends javax.swing.JDialog {

    /** Creates new form ModificaModPagamento */
    public ModificaModPagamento(java.awt.Frame parent, boolean modal, Fattura fattura) {
        super(parent, modal);
        initComponents();
        this.parent = (RegistroFattureEmesse) parent;
        this.fattura = fattura;
        String[] metPagam = FrontController.getMetodiPagamento();
        for (int i = 1; i < metPagam.length; i++)
            cboMetPag.addItem((String) metPagam[i]);
        
        metPagam = fattura.getMetPag().split("-");
        cboMetPag.setSelectedItem((String) metPagam[0]);
        cboGiorni.setSelectedItem((String) metPagam[1]);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        cboMetPag = new javax.swing.JComboBox();
        cboGiorni = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnAnnulla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuova modalità di pagamento");
        setResizable(false);

        jLabel9.setText("Pagamento");

        cboGiorni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85", "90", "95", "100", "105", "110", "115", "120" }));

        jLabel10.setText("Giorni");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnAnnulla.setText("Annulla");
        btnAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnullaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(cboMetPag, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboGiorni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAnnulla)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboGiorni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cboMetPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnnulla)
                    .addComponent(btnOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnullaActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_btnAnnullaActionPerformed

private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
// TODO add your handling code here:
    String vecchioMetodo = fattura.getMetPag();
    fattura.setMetPag(cboMetPag.getSelectedItem() + "-" + cboGiorni.getSelectedItem());
    if (FrontController.updateMetodoPagamento(fattura)) {
        parent.setFatture();
        dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Si è verificato un errore durante la modifica!", "Errore", JOptionPane.ERROR_MESSAGE);
        fattura.setMetPag(vecchioMetodo);
    }
    

}//GEN-LAST:event_btnOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnulla;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cboGiorni;
    private javax.swing.JComboBox cboMetPag;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private RegistroFattureEmesse parent;
    private Fattura fattura;
}