/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NotePagamento.java
 *
 * Created on 21-giu-2012, 22.15.11
 */
package viste;

import controllo.FrontController;
import entita.Fattura;
import entita.Movimento;
import java.awt.Color;
import java.awt.Frame;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import libs.DoubleFormatter;

/**
 *
 * @author Michele
 */
public class NotePagamento extends javax.swing.JDialog {

    /** Creates new form NotePagamento */
    public NotePagamento(java.awt.Frame parent, boolean modal, Fattura fattura) {
        super(parent, modal);
        this.fattura = fattura;
        this.metodiPagamento = FrontController.getMetodiPagamento();
        initComponents();
        ColorManager color = new ColorManager();
        color.changeColor(pnl);

        txtMetodi = new javax.swing.JTextField[] {
            null, txtContante, txtBonifico, txtAssegno, txtRiba
        };
        
        this.parent = parent;
        setTitle(getTitle() + ": totale fattura " + fattura.getTotale());
    }
    //Costruttore per la modifica live dei metodi di pagamento
    public NotePagamento(javax.swing.JDialog parent, boolean modal, Fattura fattura) {
        super(parent, modal);
        this.fattura = fattura;
        this.metodiPagamento = FrontController.getMetodiPagamento();
        initComponents();
        ColorManager color = new ColorManager();
        color.changeColor(pnl);
        //JOptionPane.showMessageDialog(rootPane, "ECCOMI");
        calledByDialog = true;
        txtMetodi = new javax.swing.JTextField[] {
            null, txtContante, txtBonifico, txtAssegno, txtRiba
        };
        
        this.dialogParent = parent;
        setTitle(getTitle() + ": totale fattura " + fattura.getTotale());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl = new javax.swing.JPanel();
        lblContante = new javax.swing.JLabel();
        lblBonifico = new javax.swing.JLabel();
        lblAssegno = new javax.swing.JLabel();
        lblRiba = new javax.swing.JLabel();
        txtContante = new javax.swing.JTextField();
        txtBonifico = new javax.swing.JTextField();
        txtAssegno = new javax.swing.JTextField();
        txtRiba = new javax.swing.JTextField();
        btnConferma = new javax.swing.JButton();
        btnAnnulla = new javax.swing.JButton();
        lblRiba1 = new javax.swing.JLabel();
        txtTot = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modalità di pagamento");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lblContante.setText("Contante");

        lblBonifico.setText("Bonifico Bancario");

        lblAssegno.setText("Assegno Bancario");

        lblRiba.setText("RIBA");

        txtContante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContanteFocusLost(evt);
            }
        });

        txtBonifico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBonificoFocusLost(evt);
            }
        });

        txtAssegno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAssegnoFocusLost(evt);
            }
        });

        txtRiba.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRibaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContante)
                    .addComponent(lblRiba)
                    .addComponent(lblAssegno)
                    .addComponent(lblBonifico))
                .addGap(55, 55, 55)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRiba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAssegno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBonifico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContante, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pnlLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAssegno, lblBonifico, lblContante, lblRiba});

        pnlLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAssegno, txtBonifico, txtContante, txtRiba});

        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContante)
                    .addComponent(txtContante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBonifico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBonifico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAssegno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAssegno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRiba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRiba))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConferma.setBackground(new java.awt.Color(255, 255, 255));
        btnConferma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        btnConferma.setText("Conferma");
        btnConferma.setToolTipText("Conferma");
        btnConferma.setMargin(new java.awt.Insets(2, -10, 2, 14));
        btnConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfermaActionPerformed(evt);
            }
        });

        btnAnnulla.setBackground(new java.awt.Color(255, 255, 255));
        btnAnnulla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/annulla.png"))); // NOI18N
        btnAnnulla.setText("Annulla");
        btnAnnulla.setToolTipText("Annulla");
        btnAnnulla.setMargin(new java.awt.Insets(2, -10, 2, 14));
        btnAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnullaActionPerformed(evt);
            }
        });

        lblRiba1.setText("Totale inserito");

        txtTot.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtTot.setForeground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConferma, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAnnulla)))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblRiba1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnnulla, btnConferma});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRiba1)
                    .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConferma)
                    .addComponent(btnAnnulla))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
    
    if (fattura.getNotePag() == null) {
        String metPag = (fattura.getMetPag().split("-"))[0];
        double totale = DoubleFormatter.roundTwoDecimals(fattura.getTotale());
    
        for (int i = 1; i < txtMetodi.length; i++)
            if (metPag.equals(metodiPagamento[i])) {
                txtMetodi[i].setText(String.valueOf(totale));
                break;
            }
    } else {
        List<Movimento> movimenti = fattura.getMovimenti();
        for (Movimento movimento : movimenti) {
            for (int i = 1; i < txtMetodi.length; i++)
                if (movimento.getMetPag().equals(metodiPagamento[i])) {
                    txtMetodi[i].setText(String.valueOf(movimento.getValore()));
                    break;
                }
        }
    }
    
    checkInsertedTotal();
            
}//GEN-LAST:event_formWindowOpened

private void checkInsertedTotal(){
    double tot = 0.00;
    for (int i = 1; i < txtMetodi.length; i++){
        double val = 0.00;
        if (!(txtMetodi[i].getText().equalsIgnoreCase("")))
           val = Double.parseDouble(txtMetodi[i].getText());
        tot += val;
    }
    txtTot.setText(String.valueOf(tot));
    if (tot != fattura.getTotale())
        txtTot.setForeground(Color.red);
    else txtTot.setForeground(Color.green);
}

private void btnAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnullaActionPerformed
// TODO add your handling code here:
    if (!calledByDialog){
        try {
        ((RegistroFattureEmesse)parent).setFatture();
        
        } catch (ClassCastException e) {
            ((RegistroFattureAcquisto)parent).setFatture();
        }
    } else {
        ((InsFatturaAcquisto)dialogParent).movimenti = null;
    }
    dispose();
}//GEN-LAST:event_btnAnnullaActionPerformed

private void btnConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermaActionPerformed
// TODO add your handling code here:
    double[] valori = new double[txtMetodi.length -1];
    double somma = 0.00;
    for (int i = 0; i < txtMetodi.length -1; i++) {
        String valore = txtMetodi[i + 1].getText();
        if (!valore.isEmpty()) {
            try {
                valori[i] = DoubleFormatter.roundTwoDecimals(Double.parseDouble(valore));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Valore errato per il metodo " + metodiPagamento[i + 1] + "!", "Formato errato", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
        } else {
            valori[i] = 0.00;
        }
        
        somma += valori[i];
    }
        
    if (somma != fattura.getTotale()) {
        JOptionPane.showMessageDialog(this, "La somma di tutti i valori inseriti non coincide con il totale della fattura!\nSi prega di ricontrollare i valori inseriti",
                "Errore", JOptionPane.ERROR_MESSAGE);
        
    } else {
        List<Movimento> movimenti = new LinkedList<Movimento>();
        Fattura.tipo tipo;
        if (parent instanceof RegistroFattureEmesse)
            tipo = Fattura.tipo.VEN;
        else
            tipo = Fattura.tipo.ACQ;
        
        
        for (int i = 0; i < valori.length; i++)
            if (valori[i] != 0.00)
                movimenti.add(new Movimento(fattura.getNumero(), fattura.getData(), tipo.toString(), metodiPagamento[i + 1], valori[i], fattura.getCliente().getCod()));
        
        if (!calledByDialog){
            FrontController.updatePagataFattura(tipo, fattura, true, movimenti);
        
            if (tipo == Fattura.tipo.VEN) {
                ((RegistroFattureEmesse)parent).setFatture();
            
            } else {
                ((RegistroFattureAcquisto)parent).setFatture();
            }
        } else {
            ((InsFatturaAcquisto)dialogParent).movimenti = movimenti; 
        }
        
        dispose();
    }
    
    
}//GEN-LAST:event_btnConfermaActionPerformed

private void txtContanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContanteFocusLost
// TODO add your handling code here:
    checkInsertedTotal();
}//GEN-LAST:event_txtContanteFocusLost

private void txtBonificoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBonificoFocusLost
// TODO add your handling code here:
    checkInsertedTotal();
}//GEN-LAST:event_txtBonificoFocusLost

private void txtAssegnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAssegnoFocusLost
// TODO add your handling code here:
    checkInsertedTotal();
}//GEN-LAST:event_txtAssegnoFocusLost

private void txtRibaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRibaFocusLost
// TODO add your handling code here:
    checkInsertedTotal();
}//GEN-LAST:event_txtRibaFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnulla;
    private javax.swing.JButton btnConferma;
    private javax.swing.JLabel lblAssegno;
    private javax.swing.JLabel lblBonifico;
    private javax.swing.JLabel lblContante;
    private javax.swing.JLabel lblRiba;
    private javax.swing.JLabel lblRiba1;
    private javax.swing.JPanel pnl;
    private javax.swing.JTextField txtAssegno;
    private javax.swing.JTextField txtBonifico;
    private javax.swing.JTextField txtContante;
    private javax.swing.JTextField txtRiba;
    private javax.swing.JTextField txtTot;
    // End of variables declaration//GEN-END:variables

    private Fattura fattura;
    private javax.swing.JTextField txtMetodi[];
    private Frame parent;
    private JDialog dialogParent;
    private boolean calledByDialog = false;
    private String[] metodiPagamento;
}
