/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PagamentoFattura.java
 *
 * Created on 20-mag-2012, 0.19.14
 */
package viste;

import controllo.FrontController;
import eccezioni.CheckTuttException;
import java.sql.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author Michele
 */
public class PagamentoFattura extends javax.swing.JDialog {

    public PagamentoFattura() {
    }    
    
    /** Creates new form PagamentoFattura */
    public PagamentoFattura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ColorManager color = new ColorManager();
        color.changeColor(pnlDati);
    }

    public PagamentoFattura(InsSpedizione aThis, boolean modal) {
        super(aThis, modal);
        initComponents();
        ColorManager color = new ColorManager();
        color.changeColor(pnlDati);
        insSpedizione = aThis;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        btnOk = new javax.swing.JButton();
        btnAnnulla = new javax.swing.JButton();
        pnlDati = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNote = new javax.swing.JTextField();
        txtMese = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboGiorni = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        chkPagata = new javax.swing.JCheckBox();
        chkForfait = new javax.swing.JCheckBox();
        txtNFatt = new javax.swing.JTextField();
        txtGiorno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAnno = new javax.swing.JTextField();
        cboMetPag = new javax.swing.JComboBox();
        jLabel48 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modalità di pagamento");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnOk.setBackground(new java.awt.Color(255, 255, 255));
        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        btnOk.setText("OK");
        btnOk.setToolTipText("Completa la fatturazione");
        btnOk.setMargin(new java.awt.Insets(2, -10, 2, 14));
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnAnnulla.setBackground(new java.awt.Color(255, 255, 255));
        btnAnnulla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/annulla.png"))); // NOI18N
        btnAnnulla.setText("Annulla");
        btnAnnulla.setToolTipText("Annulla");
        btnAnnulla.setMargin(new java.awt.Insets(2, -10, 2, 14));
        btnAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnullaActionPerformed(evt);
            }
        });

        pnlDati.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dati Fattura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel2.setText("Pagamento");

        txtMese.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMeseFocusLost(evt);
            }
        });

        jLabel4.setText("Note");

        cboGiorni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85", "90", "95", "100", "105", "110", "115", "120" }));

        jLabel11.setText("mm");

        chkPagata.setFont(new java.awt.Font("Tahoma", 1, 12));
        chkPagata.setText("Fattura pagata");

        chkForfait.setFont(new java.awt.Font("Tahoma", 1, 12));
        chkForfait.setText("Fattura forfettaria");

        txtNFatt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNFattFocusLost(evt);
            }
        });

        txtGiorno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGiornoFocusLost(evt);
            }
        });

        jLabel9.setText("Data Fattura");

        jLabel3.setText("Giorni");

        jLabel10.setText("gg");

        txtAnno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAnnoFocusLost(evt);
            }
        });

        jLabel48.setText("# Fattura");

        jLabel12.setText("aaaa");

        javax.swing.GroupLayout pnlDatiLayout = new javax.swing.GroupLayout(pnlDati);
        pnlDati.setLayout(pnlDatiLayout);
        pnlDatiLayout.setHorizontalGroup(
            pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatiLayout.createSequentialGroup()
                            .addComponent(jLabel48)
                            .addGap(14, 14, 14)
                            .addComponent(txtNFatt))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatiLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(29, 29, 29)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtGiorno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMese, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatiLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(chkForfait)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkPagata))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatiLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(14, 14, 14)
                            .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNote, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cboMetPag, javax.swing.GroupLayout.Alignment.TRAILING, 0, 246, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cboGiorni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatiLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtGiorno, txtMese});

        pnlDatiLayout.setVerticalGroup(
            pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtGiorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtMese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNFatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48))
                .addGap(18, 18, 18)
                .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboGiorni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cboMetPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnlDatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkForfait)
                    .addComponent(chkPagata))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnnulla, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlDati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnnulla, btnOk});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnAnnulla))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnullaActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_btnAnnullaActionPerformed

private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
// TODO add your handling code here:
    int numFattura = Integer.parseInt(txtNFatt.getText());
    String anno = txtAnno.getText();
    String mese = txtMese.getText();
    String giorno = txtGiorno.getText();
    Date dataFattura = Date.valueOf(anno + "-" + mese + "-" + giorno);
    
    if (anno.length() == 2)
        anno = "20" + anno;
    
    if (mese.length() == 1)
        mese = "0" + mese;
    
    if (giorno.length() == 1) 
        giorno = "0" + giorno;
    
    if (anno.isEmpty() || mese.isEmpty() || giorno.isEmpty()) { //Un o più campi fra gg, mm e aaaa non sono stati inseriti
        JOptionPane.showMessageDialog(null, "Inserire la data fattura nel formato gg mm aaaa", 
            "Campo obbligatorio mancante", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
     /*
     * Se la data non è inserita nel formato corretto, mostra un messaggio di errore.
     * Per formato corretto si intende che il giorno non superi 31, o che il mese non
     * sia superiore a 12, oppure che sia stato inserito il giorno corretto in base al 
     * mese inserito. (es. il 31/11 non esiste)
     */
    try {
        dataFattura = Date.valueOf(anno + "-" + mese + "-" + giorno);
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(null, "Valore inserito per la data fattura non valido! Inserire la data nel formato gg/mm/aaaa", 
            "Formato errato", JOptionPane.ERROR_MESSAGE);
            return;
    }
    
    /*int checkValue;
    checkValue = FrontController.checkForcedNumber(dataFattura, numFattura);
    System.out.println(checkValue);
    if (checkValue == -2) {
        JOptionPane.showMessageDialog(null, "La data di fatturazione è inferiore alla fattura precedente, modificala", 
                "Errore data", JOptionPane.ERROR_MESSAGE);
    }else if (checkValue == -1){
        JOptionPane.showMessageDialog(null, "Il numero di fattura inserito è già esistente nell'anno di esercizio", 
                "Errore numero fattura", JOptionPane.ERROR_MESSAGE);
    }else if (checkValue == 1) { */
        String modPag = null;

        if (cboMetPag.getSelectedIndex() > 0) {
            modPag = (String) cboMetPag.getSelectedItem() + "-" + cboGiorni.getSelectedItem();

        } else {
            modPag = "Contante-0";
        }
        String note = txtNote.getText();
        boolean pagata = chkPagata.isSelected();
        boolean forfait = chkForfait.isSelected();
        try {
            FrontController.checkTutt(dataFattura, numFattura);
            insSpedizione.continuaEmissione(numFattura, dataFattura, modPag, pagata, forfait, note);
            dispose();
            
        } catch (CheckTuttException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
        
    
}//GEN-LAST:event_btnOkActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
    txtGiorno.setDocument(new JTextFieldLimit(MAX_LENGTH_GIORNO));
    txtMese.setDocument(new JTextFieldLimit(MAX_LENGTH_MESE));
    txtAnno.setDocument(new JTextFieldLimit(MAX_LENGTH_ANNO));
    
    String[] metPagam = FrontController.getMetodiPagamento();
    for (String metodo : metPagam)
        cboMetPag.addItem((String) metodo);
    
    //Inserisce una data presunta della fattura
    java.util.Date utilDate = new java.util.Date();
    String today = (new java.sql.Date(utilDate.getTime())).toString();
    String[] splitted = today.split("\\-");
    String anno = splitted[0];
    String mese = splitted[1];
    String giorno = splitted[2];
    txtAnno.setText(anno);
    txtMese.setText(mese);
    txtGiorno.setText(giorno);
    dataPresunta = Date.valueOf(anno + "-" + mese + "-" + giorno);
    try {
        txtNFatt.setText(String.valueOf(FrontController.checkTutt(dataPresunta, -1)));
        
    } catch (CheckTuttException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Errore", JOptionPane.ERROR_MESSAGE);
    }
    
}//GEN-LAST:event_formWindowOpened

private void setNumber() {
    String anno = txtAnno.getText();
    String mese = txtMese.getText();
    String giorno = txtGiorno.getText();
    dataPresunta = Date.valueOf(anno + "-" + mese + "-" + giorno);
    int textNumber = Integer.parseInt(txtNFatt.getText());
    if (forced) {
        try {
            FrontController.checkTutt(dataPresunta, textNumber);
            
        } catch (CheckTuttException e) {
//            JOptionPane.showMessageDialog(this, e.getMessage(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
        
    } else {
        int numCheck;
        try {
            numCheck = FrontController.checkTutt(dataPresunta, -1);
            txtNFatt.setText(String.valueOf(numCheck));
            
        } catch (CheckTuttException e) {
//            JOptionPane.showMessageDialog(this, e.getMessage(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
        
    }
}

private void txtAnnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnnoFocusLost
    setNumber();
}//GEN-LAST:event_txtAnnoFocusLost


private void txtGiornoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGiornoFocusLost
// TODO add your handling code here:
    setNumber();
}//GEN-LAST:event_txtGiornoFocusLost

private void txtMeseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMeseFocusLost
// TODO add your handling code here:
   setNumber();
}//GEN-LAST:event_txtMeseFocusLost

private void txtNFattFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNFattFocusLost
// TODO add your handling code here:
    //proposedNumber è il numero ottenuto dal sistema sulla base della data all'interno delle text
    int proposedNumber;
    try {
        proposedNumber = FrontController.checkTutt(dataPresunta, -1);
    } catch (CheckTuttException e) {
//       JOptionPane.showMessageDialog(this, e.getMessage(), "Errore", JOptionPane.ERROR_MESSAGE);
       return;
       
    }
    //textNumber è il numero eventualmente inserito all'interno della text
    int textNumber = Integer.parseInt(txtNFatt.getText());
    
    //se i numeri divergono, c'è stata una forzatura da parte dell'utente
    if (textNumber != proposedNumber) {
        forced = true;
        try {
            FrontController.checkTutt(dataPresunta, textNumber);
            
        } catch (CheckTuttException e) {
//            JOptionPane.showMessageDialog(this, e.getMessage(), "Errore", JOptionPane.ERROR_MESSAGE);
//            txtNFatt.requestFocus();
            return;
        }
    }

}//GEN-LAST:event_txtNFattFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnulla;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cboGiorni;
    private javax.swing.JComboBox cboMetPag;
    private javax.swing.JCheckBox chkForfait;
    private javax.swing.JCheckBox chkPagata;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlDati;
    private javax.swing.JTextField txtAnno;
    private javax.swing.JTextField txtGiorno;
    private javax.swing.JTextField txtMese;
    private javax.swing.JTextField txtNFatt;
    private javax.swing.JTextField txtNote;
    // End of variables declaration//GEN-END:variables
    private InsSpedizione insSpedizione;
    private Date dataPresunta;
    private boolean forced = false;
    
    private static final int MAX_LENGTH_GIORNO = 2;
    private static final int MAX_LENGTH_MESE = 2;
    private static final int MAX_LENGTH_ANNO = 4;
}
